tosca_definitions_version: cloudify_dsl_1_3

node_templates:
  ovs_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: odl_key_public }
        write_files:
          - path: /etc/yum.repos.d/naulinux-extras.repo
            owner: root:root
            permissions: '0444'
            content: |
              [naulinux-extras]
              name=NauLinux Extras
              baseurl=http://downloads.naulinux.ru/pub/NauLinux/7/$basearch/Extras/RPMS/
              enabled=0
              gpgcheck=1
              gpgkey=http://downloads.naulinux.ru/pub/NauLinux/RPM-GPG-KEY-linux-ink
        runcmd:
          - [dhclient]
          - [yum, -y, --enablerepo=naulinux-extras, install, openvswitch]
          - [/usr/share/openvswitch/scripts/ovs-ctl, start]
          - [ovs-vsctl, set-manager, 'ptcp:6640']

  odl_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: odl_key_public }
        packages:
          - [wget]
          - [java-1.8.0-openjdk]
        runcmd:
          - [dhclient]
          - [cd, /home/centos]
          - [wget, "https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.6.2-Carbon/distribution-karaf-0.6.2-Carbon.tar.gz"]
          - [tar, -xf, distribution-karaf-0.6.2-Carbon.tar.gz]
          - [sed, -i, '/^featuresBoot=/  s/$/,odl-unimgr-ovs-driver/', distribution-karaf-0.6.2-Carbon/etc/org.apache.karaf.features.cfg]
          - [/home/centos/distribution-karaf-0.6.2-Carbon/bin/start]

  server_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: odl_key_public }
        packages:
          - [screen]
        runcmd:
          - [dhclient]
          - [screen, -d, -m, python, -m, SimpleHTTPServer, 8080]

  client_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: odl_key_public }
        runcmd:
          - [dhclient]