tosca_definitions_version: cloudify_dsl_1_3

node_templates:
  ovs_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_input: ssh_key_public }
        yum_repos:
          naulinux-extras:
            baseurl: http://downloads.naulinux.ru/pub/NauLinux/7/$basearch/Extras/RPMS/
            enabled: true
            gpgcheck: true
            gpgkey: http://downloads.naulinux.ru/pub/NauLinux/RPM-GPG-KEY-linux-ink
            name: NauLinux Extras
        write_files:
          - path: /etc/sysconfig/network-scripts/ifcfg-eth1
            owner: root:root
            permissions: '0644'
            content: |
              DEVICE="eth1"
              BOOTPROTO="dhcp"
              ONBOOT="yes"
              TYPE="Ethernet"
              USERCTL="yes"
              PEERDNS="no"
              IPV6INIT="no"
              PERSISTENT_DHCLIENT="1"
          - path: /etc/sysconfig/network-scripts/ifcfg-eth2
            owner: root:root
            permissions: '0644'
            content: |
              DEVICE="eth2"
              BOOTPROTO="dhcp"
              ONBOOT="yes"
              TYPE="Ethernet"
              USERCTL="yes"
              PEERDNS="no"
              IPV6INIT="no"
              PERSISTENT_DHCLIENT="1"
        packages:
          - openvswitch
        runcmd:
          - [systemctl, restart, network]
          - [/usr/share/openvswitch/scripts/ovs-ctl, start]
          - [ovs-vsctl, set-manager, 'ptcp:6640']

  odl_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_input: ssh_key_public }
        packages:
          - [wget]
          - [java-1.8.0-openjdk]
        runcmd:
          - [systemctl, restart , network]
          - [cd, /home/centos]
          - [wget, "https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/distribution-karaf/0.6.2-Carbon/distribution-karaf-0.6.2-Carbon.tar.gz"]
          - [tar, -xf, distribution-karaf-0.6.2-Carbon.tar.gz]
          - [sed, -i, '/^featuresBoot=/  s/$/,odl-unimgr-ovs-driver/', distribution-karaf-0.6.2-Carbon/etc/org.apache.karaf.features.cfg]
          - [/home/centos/distribution-karaf-0.6.2-Carbon/bin/start]

  server_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_input: ssh_key_public }
        packages:
          - [screen]
        write_files:
          - path: /etc/sysconfig/network-scripts/ifcfg-eth1
            owner: root:root
            permissions: '0644'
            content: |
              DEVICE="eth1"
              BOOTPROTO="dhcp"
              ONBOOT="yes"
              TYPE="Ethernet"
              USERCTL="yes"
              PEERDNS="no"
              IPV6INIT="no"
              PERSISTENT_DHCLIENT="1"
        runcmd:
          - [systemctl, restart, network]
          - [screen, -d, -m, python, -m, SimpleHTTPServer, 8080]

  client_cloud_config:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        users:
          - name: centos
            primary-group: wheel
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_input: ssh_key_public }
        write_files:
          - path: /etc/sysconfig/network-scripts/ifcfg-eth1
            owner: root:root
            permissions: '0644'
            content: |
              DEVICE="eth1"
              BOOTPROTO="dhcp"
              ONBOOT="yes"
              TYPE="Ethernet"
              USERCTL="yes"
              PEERDNS="no"
              IPV6INIT="no"
              PERSISTENT_DHCLIENT="1"
        runcmd:
          - [systemctl, restart, network]
